title: Cyber Mind Palace
author:
  name: Nick Cui
  email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  A cyber mind palace for memorizing thoughts, solutions, inspiration, and unbridled imagination,
  life wisedom, book review, etc.


# Building settings

theme: minima

minima:
  skin: auto

