title: Cyber Mind Palace

author: Nick Cui

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  A cyber mind palace for memorizing thoughts, solutions, inspiration, and unbridled imagination,
  life wisedom, book review, etc.


# Building settings

theme: minima